apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: external-llm-workflow
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: call-external-llm
            template: external-llm

    - name: external-llm
      inputs:
        parameters:
          - name: prompt
      container:
        image: iomaiph/external-llm:latest
        command: [python, /app/main.py]
        env:
          - name: EXTERNAL_LLM_API_KEY
            valueFrom:
              secretKeyRef:
                name: external-llm-secret
                key: api-key
